name: Code sniffer
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  code_sniffer:
    name: Code sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install system dependencies
        run: composer install
      - name: Run code sniffer
        run: |
          vendor/bin/phpcs --standard=phpcs.ruleset.xml -v .
